{% set version = "4.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-broomextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broomExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broomExtra/broomExtra_{{ version }}.tar.gz
  sha256: 484d2b78a822795406460f94ae9f6f42a03bd0a0e5ff7e324cb54a8667648669

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [r_base == '3.5.1']
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom
    - r-broom.mixed
    - r-dplyr
    - r-ipmisc
    - r-parameters
    - r-performance
    - r-rlang
  run:
    - r-base
    - r-broom
    - r-broom.mixed
    - r-dplyr
    - r-ipmisc
    - r-parameters
    - r-performance
    - r-rlang

test:
  commands:
    - $R -e "library('broomExtra')"           # [not win]
    - "\"%R%\" -e \"library('broomExtra')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/broomExtra/, https://github.com/IndrajeetPatil/broomExtra
  license: GPL-3
  summary: Collection of functions to assist 'broom' and 'broom.mixed' package-related data analysis workflows. In particular, the generic functions tidy(), glance(),
    and augment() choose appropriate S3 methods from these two packages depending on which package exports the needed method. Additionally, 'grouped_' and 'boot_'
    variants of the generics provides a convenient way to execute functions across a combination of grouping variable(s) in a dataframe or bootstrap them.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: broomExtra
# Title: Enhancements for 'broom' Package Family
# Version: 0.0.5
# Authors@R:  person(given = "Indrajeet", family = "Patil", role = c("aut", "cre", "ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531"))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Collection of functions to assist 'broom' and 'broom.mixed' package-related data analysis workflows. In particular, the generic functions tidy(), glance(), and augment() choose appropriate S3 methods from these two packages depending on which package exports the needed method. Additionally, 'grouped_' and 'boot_' variants of the generics provides a convenient way to execute functions across a combination of grouping variable(s) in a dataframe or bootstrap them.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/broomExtra/, https://github.com/IndrajeetPatil/broomExtra
# BugReports: https://github.com/IndrajeetPatil/broomExtra/issues
# Depends: R (>= 3.5.0)
# Imports: broom (>= 0.5.2), broom.mixed (>= 0.2.4), dplyr (>= 0.8.1), magrittr (>= 1.5), purrr (>= 0.3.2), rlang (>= 0.4.0), rsample (>= 0.0.4), tidyr (>= 0.8.3), utils
# Suggests: generics, ggplot2, knitr, lme4, rmarkdown, spelling, stringr, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1.9000
# NeedsCompilation: no
# Packaged: 2019-08-19 12:01:34 UTC; inp099
# Author: Indrajeet Patil [aut, cre, ctb] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2019-08-19 13:30:06 UTC
