travis:
  secure:
    BINSTAR_TOKEN: Mvh9BdW56tIiDI6eDuYoHiNTSJDbeFHB5OR3komLBFG07omHe6E+id6DXJEPkHnY+vrO9buYj7v1D4yAf1A1uz9udtSFYUpjN703bJ20IeECCuM19PaMmyt6OiGrBKQwEVtUwUsQ9VFKImn0/ozS3PZcelMQ+XVdZ2fgrkDGauVmNCFERRbZgQCuwPQAtID/FSwJn3+t2EeRzNmTmpKq04GiyHVvYlY68wkHWcJoAj2q6C48Wx5IDTWDT01vn7Eo4n1CwrDNuM/ZdOAwLVh/spw75ZfbugyGSriwv4AobR9nXmynJZ88It3+giQWodHNeW0oTzmnioGPz12bwqNPuc4RrH12MaDyz647cdZpRaK5SWxXQdyd9/tpkQ5FRvUeGl6Dqd2EkP8WOTXGv04CsXDO/7og+eMPpu3vL61SyfZVlRp3yT+VQQqa1JpChHd6meFklGSjBxgzCwOMc/fhvrIYy59043CTTpL64GFSLB9YEE4y3UXjHJYj/aSJ6AmnJd4douRHfqh7AybRA11Hi7Ib9oB1T5Vlo3SxyeNC5ekGnfvTi+IImj0vQoxBhDDc4bhJSCSMWBEf1aIxhl6Aj+57DTO46qqCYnGT6dX8O3mVjOpN8YIuLGC7NXUFn4NpxShS0m5pu9tCsH98NmEUiA7amUlNz8l3/Ysmhl2sGSg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
